---
- name: deploy Geocitizen app
  hosts: localhost
  gather_facts: yes
  become: yes
  pre_tasks:
    - name: load inventory
      set_fact:
        db_host: "{{ hostvars['db_server'].ansible_host }}:5432"
        db_name: "{{ hostvars['db_server'].db_name }}" 
        db_username: "{{ hostvars['db_server'].db_username }}" 
        db_password: "{{ hostvars['db_server'].db_password }}" 
        map_api_key: "{{ hostvars['map_key'].key }}"

    - name: Copy repository
      git:
        repo: https://github.com/gazpacho-cloud/geocit.git
        dest: /geocit
        force: yes

    - name: Change configuration for DB
      replace:
        path: /geocit/src/main/resources/application.properties
        regexp: 'localhost:5432'
        replace: "{{ hostvars['db_server'].ansible_host }}:5432"

    - name: Change configuration for front-end
      replace:
        path: /geocit/src/main/resources/application.properties
        regexp: 'localhost:8080'
        replace: "{{ hostvars['app'].ansible_host }}:8080"

    - name: Change configuration in application.properties
      lineinfile:
        path: /geocit/src/main/resources/application.properties
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^db\.url=', line: 'db.url=jdbc:postgresql://{{ db_host }}/{{ db_name }}' }
        - { regexp: '^db\.username=', line: 'db.username={{ db_username }}' }
        - { regexp: '^db\.password=', line: 'db.password={{ db_password }}' }
        - { regexp: '^map\.key=', line: 'map.key={{ map_api_key }}' }

    - name: Change configuration in js
      replace:
        path: /geocit/src/main/webapp/static/js/app.6313e3379203ca68a255.js
        regexp: 'localhost'
        replace: "{{ hostvars['app'].ansible_host }}"

  roles:
    - maven
    - tomcat