- name: Download Docker installation script
  command: curl -fsSL https://get.docker.com/ -o get-docker.sh
  args:
    chdir: /tmp

- name: Run Docker installation script
  command: sudo sh get-docker.sh
  args:
    chdir: /tmp

- name: Add user to the Docker group
  user:
    name: "{{ansible_user_id}}"
    groups: docker
    append: yes

- name: Verify docker group membership
  shell: groups
  register: group_membership

- name: Install pip (if not already installed)
  apt:
    name: python3-pip
    state: present
  become: yes

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: present
  become: yes

- name: Create JFrog directories
  file:
    path: "{{jfrog_home}}/artifactory/var/etc/"
    state: directory
    recurse: yes

- name: Create system.yaml file
  file:
    path: "{{jfrog_home}}/artifactory/var/etc/system.yaml"
    state: touch

- name: Change ownership of JFrog directory
  file:
    path: "{{jfrog_home}}/artifactory/var"
    state: directory
    owner: "{{artifactory_uid}}"
    group: "{{artifactory_gid}}"
    recurse: yes

- name: Run JFrog Artifactory container
  docker_container:
    name: artifactory
    image: "{{artifactory_image}}"
    state: started
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - "{{jfrog_home}}/artifactory/var/:/var/opt/jfrog/artifactory"