- name: Install PostgreSQL and setup database
  hosts: dbservers
  become: 'yes'
  
  vars:
    postgresql_version: '14'
    postgresql_user: postgres
    postgresql_password: postgres
    postgresql_db: ss_demo_1
- name: Ensure PostgreSQL repository is present
  apt_repository:
    repo: >-
      deb http://apt.postgresql.org/pub/repos/apt {{
      ansible_distribution_release }}-pgdg main
    state: present
    filename: pgdg
- name: Import PostgreSQL signing key
  apt_key:
    url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'
    state: present
- name: Update APT package list
  apt:
    update_cache: 'yes'
- name: Install PostgreSQL
  apt:
    name: 'postgresql-{{ postgresql_version }}'
    state: present
- name: Install PostgreSQL contrib
  apt:
    name: 'postgresql-contrib-{{ postgresql_version }}'
    state: present
- name: Ensure PostgreSQL service is enabled and started
  service:
    name: postgresql
    state: started
    enabled: 'yes'
- name: Set PostgreSQL user password
  become_user: postgres
  postgresql_user:
    name: '{{ postgresql_user }}'
    password: '{{ postgresql_password }}'
    encrypted: 'no'
    state: present
- name: Create PostgreSQL database
  become_user: postgres
  postgresql_db:
    name: '{{ postgresql_db }}'
    owner: '{{ postgresql_user }}'
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
    state: present