---
- name: add grafana gpg key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: grafana repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: update apt cache
  apt:
    update_cache: yes

- name: install grafana
  apt:
    name: grafana
    state: present

- name: check if grafana dir excists
  file:
    path: /etc/grafana/provisioning/datasources
    state: directory

- name: load grafana config
  copy:
    src: files/datasource.yml
    dest: /etc/grafana/provisioning/datasources/datasource.yml
    owner: grafana
    group: grafana
    mode: '0644'

- name: check if grafana started 
  systemd:
    name: grafana-server
    state: started
    enabled: yes
