---
- name: add prometheus repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: add prometheus GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: install prometheus
  apt:
    name: prometheus
    state: present

- name: check if prometheus dir excists
  file:
    path: /etc/prometheus
    state: directory

- name: load prometheus config
  copy:
    src: files/prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'

- name: check if prometheus started 
  systemd:
    name: prometheus
    state: started
    enabled: yes
