---
- name: deploy Geocitizen app
  hosts: geocit
  gather_facts: yes
  become: yes
  pre_tasks:
    - name: Transfer file key from control node to geocit node 
      synchronize:
        src: /var/lib/jenkins/key.file
        dest: ~/key.file

    - name: auth with GCloud
      shell: |
        gcloud auth activate-service-account --key-file ~/key.file
      when: not ansible_check_mode

    - name: get secret version for my-new-secret
      command: gcloud secrets versions access latest --secret="my-new-secret"
      register: secret_content

    - name: Parse secret JSON for my-new-secret
      set_fact:
        credentials: "{{ secret_content.stdout | from_json }}"

    - name: load inventory
      set_fact:
        db_host: "{{ credentials.db_ip }}:5432"
        db_name: "{{ credentials.db_name }}" 
        db_username: "{{ credentials.db_username }}" 
        db_password: "{{ credentials.db_password }}" 
        app_ip: "{{ credentials.app_ip }}"
        grafana_prometheus_ip: "{{ credentials.grafana_prometheus_ip }}"
        map_api_key: "{{ credentials.map_key }}"

    - name: Copy repository
      git:
        repo: https://github.com/Pharisaeuss/geocitizen.git
        dest: /geocit
        force: yes

    - name: Change configuration for DB
      replace:
        path: /geocit/src/main/resources/application.properties
        regexp: 'localhost:5432'
        replace: "{{ db_host }}"

    - name: Change configuration for front-end
      replace:
        path: /geocit/src/main/resources/application.properties
        regexp: 'localhost:8080'
        replace: "{{ app_ip }}:8080"

    - name: Change configuration in application.properties
      lineinfile:
        path: /geocit/src/main/resources/application.properties
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^db\.url=', line: 'db.url=jdbc:postgresql://{{ db_host }}/{{ db_name }}' }
        - { regexp: '^db\.username=', line: 'db.username={{ db_username }}' }
        - { regexp: '^db\.password=', line: 'db.password={{ db_password }}' }
        - { regexp: '^map\.key=', line: 'map.key={{ map_api_key }}' }

    - name: Change configuration in js
      replace:
        path: /geocit/src/main/webapp/static/js/app.6313e3379203ca68a255.js
        regexp: 'localhost'
        replace: "{{ app_ip }}"

  roles:
    - maven
    - tomcat

- name: deploy monitoring stack
  hosts: monitoring_instances
  become: yes
  pre_tasks:
    - name: get secret version for my-new-secret
      command: gcloud secrets versions access latest --secret="my-new-secret"
      register: secret_content

    - name: parse secret json for my-new-secret
      set_fact:
        credentials: "{{ secret_content.stdout | from_json }}"

    - name: inventory facts for monitoring stack
      set_fact:
        grafana_prometheus_ip: "{{ credentials.grafana_prometheus_ip }}"

    - name: grafana prometheus IP
      debug:
        msg: "grafana prometheus IP is {{ grafana_prometheus_ip }}"

  roles:
    - grafana
    - prometheus
- name: Install PostgreSQL and setup database
  hosts: dbservers
  become: 'yes'
  roles:
    - postgres
